#!/usr/bin/env bash
# Installs nginx server  and configures it on a remote server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
